### ISSUE TITLE
Spider Blocker user request

### ISSUE THREAD

**Issue by zupo** [niteoweb/spiderblocker#1]
I'm writing about your spider blocker plugin. I just saw that it does not  block SEMrush spiders from crawling PBN sites.

that's what I've found in SEMrush bot page:

"Please do not try to block SEMRushBot via IP in .htaccess as we do not use any consecutive IP blocks." 

Is it possible to add bot blocking rules to robots.txt file, not only into htaccess file?

I saw that you're not using IP's to block crawlers, but when I open my PBN's robots.txt file it's wp default http://screencast.com/t/AcPmEqgLHw

and I can find links in SEMrush when looking at money site analysis:
http://screencast.com/t/4JfXb89n

As I understand, your plugin adds records to .htaccess file, but semrush bot does not look at it:
http://screencast.com/t/eFvdXDjN

**Comment by dz0ny** [comment]
Solved with https://github.com/niteoweb/spiderblocker/commit/b015cb20e7539a5c47dd9955914725b1ea750a88
